### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by PeeHaa** [PeeHaa/mailgrab#1]
- [x] open links in html view in new tab
- [x] html view without images (render alt texts instead)
- [x] fix recipients
- [x] reconnect logic and disconnected notification
- [x] dynamic websocket url based on base url
- [x] notification on delete for other connected clients
- [x] notification on read for other connected clients
- [x] add intro page
- [x] implement history api
- [x] Web notifications
- [x] handle not found messages
- [x] implement bcc addresses
- [x] when opening mails it should default to html view and fallback to text view
- [x] cli flags for setting up server address and binding
- [x] split up this issue list toseparate issues with milestones
- [x] make the project usable on mobile
- [x] parse attachments
- [x] persistent storage
- [x] Forward mail to real inbox
- [x] provide overview of external links
- [x] handle new mails after restart (prevent duplication of mails)
- [x] phar update
- [x] implement search
